good/urls.py
from django.urls import path
from good import views
app_name = 'good'
urlpatterns = [
    path('search/', views.catalog, name= "search"),
    path('<slug:category_slug>/', views.catalog, name= "catalog"),
    path('product/<slug:product_slug>/', views.product, name= "product")

]

tira/urls.py
from doctest import debug
from re import DEBUG
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from tira import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace='main')),
    path('catalog/', include('good.urls',namespace='good')),
    path('user/', include('user.urls',namespace='user')),
    path('basket/', include('basket.urls',namespace='baskets'))


]

if settings.DEBUG : 
    urlpatterns += [
        path('__debug__/', include("debug_toolbar.urls"))
    # ... the rest of your URLconf goes here ...
    ]  

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

user/urls.py
from django.urls import path
from user import views
app_name = 'user'
urlpatterns = [
    path('login/', views.login, name= "login"),
    path('registration/', views.registration, name= "registration"),
    path('profile/', views.profile, name= "profile"),
    path('logout/', views.logout, name= "logout"),
    path('user_basket/', views.user_basket, name= "user_basket")

]

user/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
    image:Any = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name="Аватар")

    class Meta:
        db_table = "user"
        verbose_name= "Пользователь"
        verbose_name_plural = "Пользователи"
    
    def __str__(self) -> str:
        return self.username
# Create your models here.

user/forms.py
from dataclasses import field
import email
from os import name
from django import forms
from django.contrib.auth.forms import AuthenticationForm , UserCreationForm, UserChangeForm
from user.models import User

class UserLoginform(AuthenticationForm) :
    username = forms.CharField()
    password = forms.CharField()
    class Meta:
        model = User
        fields = ['username','password']

class UserRegistrationform(UserCreationForm) :
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']

class ProfileForm(UserChangeForm) :
    image = forms.ImageField(required=False) # Необязательное поле
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    class Meta:
        model = User
        fields = ['image','last_name','username','email','first_name']

user/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from traitlets import Instance
from user.forms import UserLoginform, UserRegistrationform, ProfileForm
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def login(request):
    if request.method=='POST':
        form = UserLoginform(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password'] 
            user = auth.authenticate(username=username, password=password)
            if user :
                auth.login(request,user)
                messages.success(request,f"{username} Вы успешно вошли в аккаунт")
                if request.POST.get('next',None):
                    return HttpResponseRedirect(request.POST.get('next'))
                return HttpResponseRedirect(reverse('main:index'))
                
    else:
        form = UserLoginform()
    conte = {"title":"Home - Авторизация",
             'form': form}
    return  render(request, "user/login.html",conte)

def registration(request):
    if request.method=='POST':
    
        form = UserRegistrationform(data=request.POST)
        if form.is_valid():
            form.save()
            user=form.instance
            auth.login(request,user)
            messages.success(request,f"{user.username} Вы успешно зарегистрировались")
            return HttpResponseRedirect(reverse('user:login'))
    else:
        form = UserRegistrationform()
    conte = {"title":"Home - Регистрация", "form":form }
    return  render(request, "user/registration.html",conte)
@login_required
def profile(request):
    if request.method=='POST':
        form = ProfileForm(data=request.POST, instance= request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request,"Профиль успешно обновлён")
            return HttpResponseRedirect(reverse('user:profile'))
            
    else:
        form = ProfileForm(instance=request.user)

    conte = {"title":"Home - Кабинет", "form":form}
    return  render(request, "user/profile.html",conte)
@login_required
def logout(request):
    auth.logout(request)
    messages.success(request,f"{request.user.username} Вы вышли из аккаунта")
    conte = {"title":"Home - Авторизация"}
    return redirect(reverse('main:index'))

def user_basket(request):

    return  render(request, "user/user_basket.html")

user/templates/user/login.html
{% extends "base.html" %}
{% load static  %}
{% block contents %}            <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Авторизация</h2>
                                    <form action="{% url "user:login" %}" method="post">
                                        {% csrf_token %}
                                        {% if request.GET.next %}
                                            <input type="hidden" name="next" value="{{request.GET.next}}">
                                        {% endif %}
                                        {% comment %} {{form}} {% endcomment %}
                                        <div class="mb-3">
                                            <label for="username" class="form-label">Имя пользователя</label>
                                            <input type="text" class="form-control" name="username" value="{% if form.username.value %}{{form.username.value}}{% endif %}"  id="username" placeholder="Введите ваше имя" required>
                                        </div>
                                        <div class="mb-3">
                                            <label for="password" class="form-label">Пароль</label>
                                            <input type="password" class="form-control" name="password" id="password" placeholder="Введите ваш пароль" required>
                                        </div>
                                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                                    </form>
                                    <div class="mt-3">
                                        <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration"%}">Создать аккаунт</a>
                                    </div>
                                    <hr>
                                    <div class="text-center">
                                        <p>Или авторизуйтесь через:</p>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            Google
                                        </a>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            Facebook
                                        </a>
                                        <a href="#" class="btn btn-dark">
                                            <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                                            GitHub
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock  %}

user/templates/user/profile.html
{% extends "base.html" %}
{% load static  %}
{% block contents %}   
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row">
                                <!-- Профиль с данными пользователя -->
                                <div class="col-md-5">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                                        <form action="{% url "user:profile" %}"  method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="row">
                                                {% if user.image %}
                                                <div class="col-md-12 mb-3 text-center">
                                                    <img src="{{user.image.url}}"
                                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                        style="max-width: 150px;">
                                                {% else %}
                                                <div class="col-md-12 mb-3 text-center">
                                                    <img src="{% static "deps/images/baseavatar.jpg" %}"
                                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                                        style="max-width: 150px;">
                                                {% endif %}
                                                <input type="file" class="form-control mt-3" id="avatar" name="image"
                                                        accept="image/*">
                                                        {% if  form.image.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                                    {% endif %}
                                                </div> 
                                                <div class="col-md-12 mb-3">
                                                    <label for="firstName" class="form-label">Имя*</label>
                                                    <input type="text" class="form-control" value="{{form.first_name.value}}" name="first_name" id="firstName"
                                                        placeholder="Введите ваше имя" value="" required>
                                                        {% if  form.first_name.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="lastName" class="form-label">Фамилия*</label>
                                                    <input type="text" class="form-control" name="last_name" id="lastName"
                                                        placeholder="Введите вашу фамилию" value="{{form.last_name.value}}" required>
                                                        {% if  form.last_name.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="username" class="form-label">Имя пользователя*</label>
                                                    <input type="text" class="form-control" name="username" id="username"
                                                        placeholder="Введите ваше имя пользователя" value="{{form.username.value}}" required>
                                                         {% if  form.username.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                                    {% endif %}
                                                </div>
                                                <div class="col-md-12 mb-3">
                                                    <label for="email" class="form-label">Email*</label>
                                                    <input type="email" class="form-control" name="email" id="email"
                                                        placeholder="Введите ваш email *youremail@example.com" value="{{form.email.value}}"
                                                        required>
                                                        {% if  form.email.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-dark">Сохранить</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- Корзина -->
                                <div class="col-md-7">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Корзина</h3>
                                        <div class="container" id="cart-items-container">
                                            <!-- Разметка корзины -->
                                            {% include "basket/includes/basket.html" %}
                                            <!-- Закончилась разметка корзины -->
                                        </div>
                                        <a class="btn btn-dark" href="../orders/create_order.html">
                                            Оформить заказ
                                        </a>
                                    </div>
                                </div>
                                <!-- Оформленные заказы -->
                                <div class="col-md-12">
                                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                        <h3 class="text-center mb-4">Мои заказы</h3>
                                        <!-- Разметка заказов -->
                                        <div class="container">
                                            <div class="accordion" id="accordionExample">
                                                <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading1">
                                                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                                            Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-dark table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Товар</th>
                                                                        <th>Количество</th>
                                                                        <th>Цена</th>
                                                                        <th>Общая стоимость</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                                        <td>1</td>
                                                                        <td>255.00 $</td>
                                                                        <td>255.00 $</td>
                                                                        
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                            <div class="d-flex justify-content-between">
                                                                <p><strong>Итого:</strong></p>
                                                                <p><strong>255.00 $</strong></p>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="accordion-item">
                                                    <h2 class="accordion-header" id="heading2">
                                                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                                            Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                                        </button>
                                                    </h2>
                                                    <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                                        <div class="accordion-body">
                                                            <table class="table table-dark table-hover">
                                                                <thead>
                                                                    <tr>
                                                                        <th>Товар</th>
                                                                        <th>Количество</th>
                                                                        <th>Цена</th>
                                                                        <th>Общая стоимость</th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody>
                                                                    <tr>
                                                                        <td><a class="text-white" href="#">Стул офисный</a></td>
                                                                        <td>2</td>
                                                                        <td>30.00 $</td>
                                                                        <td>60.00 $</td>
                                                                        
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Закончилась разметка заказов -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock  %}

user/templates/user/registration.html
{% extends "base.html" %}
{% load static  %}
{% block contents %}  
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Регистрация</h2>
                                    <form action="{% url "user:registration" %}"  method="POST">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="firstName" class="form-label">Имя*</label>
                                                <input type="text" value="{% if  form.first_name.value  %} {{form.first_name.value}}{% endif %}" class="form-control" id="firstName" name="first_name"
                                                    placeholder="Введите ваше имя" required>
                                                    {% if  form.first_name.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="lastName" class="form-label">Фамилия*</label>
                                                <input type="text" value="{% if  form.last_name.value  %} {{form.last_name.value}}{% endif %}" class="form-control" id="lastName" name="last_name"
                                                    placeholder="Введите вашу фамилию" required>
                                                    {% if  form.last_name.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="username"  class="form-label">Имя пользователя*</label>
                                                <input type="text" value="{% if  form.username.value  %} {{form.username.value}}{% endif %}" class="form-control" id="username" name="username"
                                                    placeholder="Введите ваше имя пользователя" required>
                                                    {% if  form.username.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="email" class="form-label">Email*</label>
                                                <input type="email" value="{% if  form.email.value  %} {{form.email.value}}{% endif %}" class="form-control" id="email" name="email"
                                                    placeholder="Введите ваш email" required>
                                                    {% if  form.email.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="password1" class="form-label">Пароль*</label>
                                                <input type="password" value="{% if  form.password1.value  %} {{form.password1.value}}{% endif %}" class="form-control" id="password1" name="password1"
                                                    placeholder="Введите пароль" required>
                                                    {% if  form.password1.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                                    {% endif %}
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="password2" class="form-label">Подтверждение пароля*</label>
                                                <input type="password" value="{% if  form.password2.value  %} {{form.password2.value}}{% endif %}" class="form-control" id="password2" name="password2"
                                                    placeholder="Подтвердите пароль" required>
                                                    {% if  form.password2.errors %}
                                                    <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                                    {% endif %}
                                            </div>
                                        </div>
                                        <button type="submit"
                                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock  %}

user/templates/user/user_basket.html
{% extends "base.html" %}
{% load static %}
{% block contents %}
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                                    <h3 class="text-center mb-4">Корзина</h3>
                                    <div class="container" id="cart-items-container">
                                        <!-- Разметка корзины -->
                                         {% include "basket/includes/basket.html" %}
                                        <!-- Закончилась разметка корзины -->
                                    </div>
                                    <a class="btn btn-dark" href="../orders/create_order.html">
                                        Оформить заказ
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock contents %}